config/routes.rb
Rails.application.routes.draw do
  get "login", to: "sessions#login", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  post "login", to: "sessions#create"
  post "/", to: "flights#result"
  root to: "flights#search"

  resources :users, only: [:new, :create] do
  end

  resources :flights do
    collection do
      get "search"
      post "search", to: "flights#result"
      get "result"
      get "all", to: "flights#all"
    end
  end

  resources :bookings, only: [:new, :edit, :update, :create, :destroy] do
    collection do
      get "/", to: "bookings#index"
      get "search", to: "bookings#search"
      post "search", to: "bookings#result"
      post "new", to: "bookings#create"
      get "confirm", to: "bookings#confirm"
      get "success", to: "bookings#success"
    end
  end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departures, class_name: "Flight", foreign_key: :departure_id
  has_many :arrivals, class_name: "Flight", foreign_key: :arrival_id
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight, foreign_key: :flight_id
  belongs_to :user, foreign_key: :user_id
  has_many :passengers
  accepts_nested_attributes_for :passengers, reject_if: :all_blank, allow_destroy: true

  before_create :set_ref
  before_save :set_seats

  def self.by_user(user_id)
    where(user_id: user_id)
  end

  private

  def set_ref
    self.ref = (0..9).to_a.sample(8).join
    set_ref if Booking.find_by_ref(ref)
  end

  def set_seats
    self.seats = passengers.length
  end
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :departure, class_name: "Airport"
  belongs_to :arrival, class_name: "Airport"
  has_many :bookings

  scope(
    :by_route,
    lambda do |from, to|
      where("departure_id = ? AND arrival_id = ?", from, to)
    end
  )

  scope :available, -> { where("departure_date >= ?", Time.now) }

  scope :by_date, ->(date) { where("departure_date = ?", date) }

  def self.per_page(page)
    Flight.offset(10 * (page.to_i - 1)).
      limit(10).order("departure_date ASC").available
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true

  before_create :format_params

  private

  def format_params
    email.downcase!
    username.capitalize!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include BookingsHelper
  def new
    @flight = Flight.find_by_id(params[:flight])
    @seats = params[:passengers]
    @booking = Booking.new
    @seats.to_i.times { @booking.passengers.build }
  end

  def create
    booking = Booking.new(bookings_params)
    booking.cost = get_cost(booking)
    booking.save
    session[:booking] = booking.id
    redirect_to confirm_bookings_path
  end

  def index
    @bookings = Booking.by_user(session[:user_id])
  end

  def edit
    @booking = Booking.find_by_id(params[:id])
    @flight = @booking.flight
    render "new"
  end

  def update
    @booking = Booking.find_by_id(params[:id])
    @booking.passengers.destroy_all
    @booking.update(bookings_params)
    @booking.cost = get_cost(@booking)
    @booking.save
    successful_update
  end

  def successful_update
    flash[:success] = "Booking Updated Successfully"
    BookingMailer.update(@booking, "Booking Updated").deliver_now
    redirect_to bookings_path
  end

  def result
    @booking = Booking.find_by_ref(params[:ref])
    flash[:notice] = "No Booking Found For That Ref"
    redirect_to :back if @booking.nil?
  end

  def destroy
    Booking.find(params[:id]).destroy
    flash[:success] = "Your Booking has Been Deleted"
    redirect_to bookings_path
  end

  def confirm
    @booking = Booking.find_by_id(session[:booking])
    @passengers = @booking.passengers
    @flight = @booking.flight
    @seats =  @booking.seats
  end

  def success
    @booking = Booking.find_by_id(params[:id])
    BookingMailer.successful(@booking, "Booking Successful").deliver_now
    @booking.update_attributes payment_status: true
  end

  def bookings_params
    params.require(:booking).permit(
      :ref,
      :seats,
      :flight_id,
      :user_id,
      :cost,
      :anon_email,
      :payment_status,
      passengers_attributes: [:name, :phone, :cabin]
    )
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def result
    @seats = params[:seats]

    if params[:date].empty?
      @flights = Flight.by_route(
        params[:departure_id],
        params[:arrival_id]).available
    else
      @flights = Flight.by_route(
        params[:departure_id],
        params[:arrival_id]
      ).by_date(params[:date])
    end

    if @flights.empty?
      flash[:notice] = "No Flights Available For That Search"
      redirect_to root_path
    end
  end

  def all
    @current_page = params[:page].to_i

    @pages = Flight.all.available.length / 10
    @flights = Flight.per_page(params[:page])
  end

  def search
    @airports = Airport.all.order("name ASC")
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def login
  end

  def create
    user = User.find_by_email(params[:email])
    password = "$2a$10$8iyAfEv9vT0vL6OHi71M8u92P8vW79Axk5Ox4lrXFGs.DHq37MVzG"
    user = User.new(password_digest: password) unless user
    if user.authenticate(params[:password])
      login_successful user
      redirect_to root_path
    else
      flash["error"] = "Invalid email/password"
      redirect_to login_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      login_successful @user
      redirect_to root_path
    else
      flash["errors"] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def users_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def get_cost(booking)
    passengers = booking.passengers
    flight = booking.flight
    passengers.each do |passenger|
      passenger.cost = case passenger.cabin
                       when "Economy" then flight.economy
                       when "First" then flight.first
                       when "Business" then flight.business
                       end
    end
    passengers.inject(0) { |cost, passenger| cost + passenger.cost }
  end

  def available?(flight_date)
    flight_date >= Time.now
  end

  def payment_url(booking)
    values = {
      business: "oluosiname-facilitator@yahoo.com",
      cmd: "_cart",
      upload: 1,
      return:  success_bookings_url(id: booking.id),
      invoice: booking.ref
    }

    booking.passengers.each_with_index do |passenger, index|
      values["amount_#{index + 1}"] = convert(passenger.cost)
      values["item_name_#{index + 1}"] = passenger.name
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  def convert(naira_cost)
    url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20"\
          "yahoo.finance.xchange%20where%20pair%20in%20(%22USDNGN%22)&"\
          "format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org"\
          "%2Falltableswithkeys&callback="
    response = RestClient.get(url)
    result = JSON.parse(response)
    exchange_rate = result["query"]["results"]["rate"]["Rate"]
    (naira_cost / exchange_rate.to_f).round(2)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_successful(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_flightinfo.html.erb
<div class="col-sm-8">
  <div class="row flight-detailss">
    <div class="row flight-details-header"><span> FLIGHT INFORMATION </span></div>
    <div class="row flight-details">
      <span class="pull-left">Flight Number:</span><span class="pull-right"><%= @flight.id %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">Airline:</span><span class="pull-right"><%= @flight.airline %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">From:  </span><span class="pull-right"><%= @flight.departure.name %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">To:</span><span class="pull-right"><%= @flight.arrival.name %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">Date:  </span><span class="pull-right"><%= @flight.departure_date %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">Take-off:  </span><span class="pull-right"><%= @flight.departure_time %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">Economy class:</span><span class="pull-right">&#x20A6;<%= @flight.economy %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">Business class:  </span><span class="pull-right">&#x20A6;<%= @flight.business %></span>
    </div>
    <div class="row flight-details">
      <span class="pull-left">First class:  </span><span class="pull-right">&#x20A6;<%= @flight.first %></span>
    </div>
  </div>
</div>

app/views/application/_footer.html.erb
<div class="my-footer">
<p>contact: noreply@bon-voyage.heroku.com</p>
<p>Tel: 08080000000</p>
<p> &copy; BonVoyage 2016 All Rights Reserved</p>

</div>

app/views/application/_header.html.erb
<div class="my-header">
  <div class="top-div">
    <ul class="pull-left">
      logo here
    </ul>
    <ul class="pull-right">
        <% if logged_in? %>
      <li class="list-inline">Welcome &nbsp; <%= @current_user.username %></li>
      <li role="presentation" class="dropdown list-inline">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          My Account <span class="caret"></span>
        </a>
        <ul class="dropdown-menu pad">
          <%= link_to bookings_path do %><li>Past Bookings</li><% end %>
          <%= link_to search_bookings_path do %><li>Manage Bookings</li><% end %>
          <%= link_to logout_path do %><li>Log Out</li><% end %>
        </ul>
      </li>
      <% else %>
      <%=link_to login_path do %><li class="list-inline"> Sign In </li><% end %>
    </ul>
    <% end %>
  </div>
</div>
<div class="low-div">
  <ul class="pull-left">
    <%=link_to all_flights_path(:page => 1) do %> <li>All Flights</li> <% end %>
    <%=link_to root_path do %><li>Search</li> <% end %>
    <%=link_to root_path do %><li>Contact us</li> <% end %>
  </ul>
</div>

app/views/application/_pagenumber.html.erb
<%= hidden_field_tag :currentPage, @current_page %>
<%= hidden_field_tag :lastPage, @pages %>
  <ul class="pagination">
  <li id="previous"><%= link_to all_flights_path(:page => (@current_page.to_i - 1)) do %>&laquo; Prev<% end %></li>
  <% for i in (1..@pages) do  %>
    <% if i == @current_page %> <li class="active"><%= link_to all_flights_path(:page => i) do %><%= i %> <% end %></li>
    <% else %>
    <li class="links"><%= link_to all_flights_path(:page => i) do %><%= i %> <% end %></li>
     <% end %>
  <% end %>
  <li id="next" ><%= link_to all_flights_path(:page => (@current_page.to_i + 1)) do %>Next &raquo;<% end %></li>
  </ul>

app/views/bookings/_passenger_fields.html.erb
<div class="nested-fields passengers">
  <div class="row div-pad">
    <div class="col-sm-5 ">
      <%= f.text_field :name, class: "form-control",  placeholder: "Name", required: "required" %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :phone, class: "form-control",  placeholder: "Phone", required: "required" %>
    </div>
    <div class="col-sm-2">
      <%= f.select(:cabin, ["Economy", "Business", "First"], {}, { :class => 'my-select' }) %>
    </div>
    <% if @booking.new_record? %>
    <div class="col-sm-1">
      <%= button_tag(type: "button", class: "btn btn-danger delete_passenger") do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/confirm.html.erb
<%= render partial: 'header' %>
<div class="container box">
  <div class="row">
    <div class="col-sm-6">
      <div class="row">
        <%= render partial: 'flightinfo' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="row confirm-head">
        <div class="col-sm-4">Name</div>
        <div class="col-sm-4">Phone</div>
        <div class="col-sm-2">cabin</div>
        <div class="col-sm-2">cost</div>
      </div>
    <% @passengers.each do |passenger| %>
      <div class="row passenger-fields">
        <div class="col-sm-4"><%= passenger.name %></div>
        <div class="col-sm-4"><%= passenger.phone %></div>
        <div class="col-sm-2"><%= passenger.cabin %></div>
        <div class="col-sm-2">&#x20A6;<%= passenger.cost %></div>
      </div>
    <% end %>
    <div class="row div-pad">
      <div class="col-sm-9">
        <%= link_to "Confirm", payment_url(@booking), class: "btn btn-success" %>
      </div>
        <div class="col-sm-2 pull-right"><span class="header-text">&#x20A6;<%= @booking.cost %></span></div>
      </div>
  </div>
</div>

app/views/bookings/index.html.erb
<%= render partial: 'header' %>
<div class="main-div">
  <div class="row bg-image">
   YOU HAVE <span class="orange-text"> <%= @bookings.length %> </span> BOOKINGS
  </div>
   <%= render partial: 'partials/userbookings' %>
</div>

app/views/bookings/make_new.html.erb
<%= render partial: 'header' %>
<div class="container box">
  <div class="row">
    <div class="col-sm-6">
      <div class="row">
      <%= render partial: 'flightinfo' %>
      </div>
    </div>
    <div class="col-sm-6">
      <%= form_for @booking do |f| %>
        <%= f.hidden_field :user_id, :value => @user %>
        <%= f.hidden_field :flight_id, :value => @flight.id %>
        <%= f.hidden_field :payment_status, :value => false %>
        <%= f.hidden_field :seats, :value => @seats %>

        <%= f.fields_for :passengers do |passengers_form| %>
        <div class="passenger-fields">
          <div class="row div-pad">
            <div class="col-sm-6">
              <%= passengers_form.text_field :first_name, class: "form-control",  placeholder: "Firstname" %>
            </div>
            <div class="col-sm-6 ">
              <%= passengers_form.text_field :last_name, class: "form-control",  placeholder: "Lastname" %>
            </div>
          </div>
          <div class="row div-pad">
            <div class="col-sm-6 ">
              <%= passengers_form.email_field :email, class: "form-control",  placeholder: "Email" %>
            </div>
            <div class="col-sm-4">
              <%= passengers_form.text_field :phone, class: "form-control",  placeholder: "Phone" %>
            </div>
            <div class="col-sm-2">
              <%= passengers_form.select(:cabin, ["Economy", "Business", "First"], {}, { :class => 'my-select' }) %>
            </div>
          </div>
        </div>
        <% end %>
          <div class="row div-pad"> <%= f.submit "Book", class: "btn btn-success"%></div>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render partial: 'header' %>
<div class="container box">
  <div class="row">
    <div class="col-sm-6">
      <div class="row">
      <%= render partial: 'flightinfo' %>
      </div>
    </div>
    <div class="col-sm-6">
      <%= form_for @booking do |f| %>
        <% unless logged_in? %>
        <div class="div-pad">You are not signed up, provide an email to receive your boking details</div>
        <div class="div-pad"> <%= f.email_field :anon_email, class: "form-control",  placeholder: "Email", required: "required"%></div>
        <% end %>
        <div><h3>PASSENGER DETAILS</h3></div>
        <% if logged_in? %> <%= f.hidden_field :user_id, :value => current_user.id %> <% end %>
        <%= f.hidden_field :flight_id, :value => @flight.id %>
        <%= f.hidden_field :payment_status, :value => false %>

        <%= f.fields_for :passengers do |passenger| %>
         <%= render 'passenger_fields', f: passenger %>
        <% end %>
        <% if @booking.new_record? %>
          <div class="div-pad">
            <%= link_to_add_association f, :passengers do %>
            <%= button_tag(type: "button", class: "btn btn-success") do %>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add <% end %>
            <% end %>
          </div>

          <div class="row div-pad-big"> <%= f.submit "Book", class: "btn orange-button"%></div>
        <% else %>
          <div class="row div-pad-big"> <%= f.submit "Update", class: "btn orange-button"%></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/result.html.erb
<%= render partial: 'header' %>
<div class="main-div">
  <div class="row bg-image">
   WE FOUND YOUR BOOKING WITH REF <span class="orange-text"> <%= @booking.ref %> </span>
  </div>
    <%= render partial: 'partials/refbooking' %>
</div>

app/views/bookings/search.html.erb
<%= render partial: 'header' %>
<div class="container search-input">
  <div class="row">
  <% unless flash['notice'].blank?  %>
   <div class="alert alert-danger search-error" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash.now['notice'] %>
  </div>
  <% end %>
  <div class="div-pad"> Search For a Past Booking </div>
    <%= form_tag %>
    <div class="input-group">
      <%= text_field_tag :ref, "", class: "form-control", placeholder: "Booking Ref..." %>
        <span class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search<% end %>
        </span>
    </div>
  </div>
</div>

app/views/flights/all.html.erb
<%= render partial: 'header' %>
<div class="main-div">
  <div class="row bg-image">
   WE FOUND <span class="orange-text"> <%= Flight.available.length %> </span> FLIGHTS FOR YOU
  </div>
  <div class="flights">
    <div class="row">
      <h3>FLIGHTS</h3>
    </div>
  <% @flights.each do |flight| %>
  <div class="flight-pad">
    </div>
    <div class="row flight-list">
      <div class="col-sm-4">
      <div class="flight-airline">
      <span><%= flight.airline %></span>
      </div>
      </div>
      <div class="col-sm-6">
        <div class="flight-detail">
          <div class="row">
            <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane"></i>
            </div>
            </div>
            <div class="col-sm-5">
              <div class="top-down-pad">  DEPARTURE </div>
              <div><%= flight.departure.name %></div>
              <div class="top-down-pad">  FROM &#x20A6;<%= flight.economy %> / PERSON</div>
              <div>
              <%= link_to "BOOK NOW", new_booking_path(:flight => flight.id, :passengers => 1), class: "btn orange-button" %>
              </div>
            </div>
            <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane arrival"></i>
            </div>
            </div>
            <div class="col-sm-5">
              <div  class="top-down-pad">  ARRIVAL </div>
              <div><%= flight.arrival.name %> </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="flight-time">
        <div class="top-down-pad">  TAKE OFF </div>
          <div><%= flight.departure_date %></div>
          <div><%= flight.departure_time %></div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row pg">
          <%= render partial: 'pagenumber' %>
     </div>
  </div>
</div>

app/views/flights/result.html.erb
<%= render partial: 'header' %>
<div class="main-div">
  <div class="row bg-image">
    WE FOUND <span class="orange-text"> <%= @flights.length %> </span> FLIGHTS FOR YOU
  </div>
  <div class="flights">
  <% @flights.each do |flight| %>
  <div class="flight-pad">
    </div>
    <div class="row flight-list">
      <div class="col-sm-4">
      <div class="flight-airline">
      <span><%= flight.airline %></span>
      </div>
      </div>
      <div class="col-sm-6">
        <div class="flight-detail">
          <div class="row">
            <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane"></i>
            </div>
            </div>
            <div class="col-sm-5">
              <div class="top-down-pad">  DEPARTURE </div>
              <div><%= flight.departure.name %></div>
              <div class="top-down-pad">  FROM <%= flight.economy %> / PERSON</div>
              <div>
              <%= link_to "BOOK NOW", new_booking_path(:flight => flight.id, :passengers => @seats), class: "btn orange-button" %>
              </div>
            </div>
            <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane arrival"></i>
            </div>
            </div>
            <div class="col-sm-5">
              <div  class="top-down-pad">  ARRIVAL </div>
              <div><%= flight.arrival.name %> </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="flight-time">
        <div class="top-down-pad">  TAKE OFF </div>
          <div><%= flight.departure_date %></div>
          <div><%= flight.departure_time %></div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bonvoyage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_arrival_select.html.erb
<div class="col-sm-4">
  <div class="div-pad"> Arrival </div>
    <select name="arrival_id" class="my-select">
    <% @airports.each do |airport| %>
      <option value="<%= airport.id %>"> <%= airport.name +  " " + airport.location %> </option>
    <% end %>
    </select>
  </div>

app/views/partials/_departure_select.html.erb
<div class="col-sm-4">
<div class="div-pad"> Departure </div>
  <select name="departure_id" class="my-select">
  <% @airports.each do |airport| %>
    <option value="<%= airport.id %>"> <%= airport.name  + " " + airport.location %> </option>
  <% end %>
  </select>
</div>

app/views/partials/_refbooking.html.erb
<div class="flights">
  <% unless flash['success'].blank?  %>
<div class="alert alert-success success-booking" role="alert">
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
  <span class="sr-only">Success:</span>
  <%= flash['success'] %>
</div>
<% end %>
    <div class="flight-pad">
  </div>
  <div class="row flight-list">
    <div class="col-sm-2">
    <div class="flight-airline">
    <span><%= @booking.flight.airline %></span>
    </div>
    </div>
    <div class="col-sm-6">
      <div class="flight-detail">
        <div class="row">
          <div class="col-sm-1">
          <div class="top-down-pad">
          <i class="fa fa-plane"></i>
          </div>
          </div>
          <div class="col-sm-5">
            <div class="top-down-pad">  DEPARTURE </div>
            <div><%= @booking.flight.departure.name %></div>
            <% if available?(@booking.flight.departure_date) %>
            <div class="top-down-pad">
              <%= link_to booking_path(@booking.id), class: "btn orange-button", method: :delete do %> <span class="large-icon"><i class="glyphicon glyphicon-trash"></i></span>
              <% end %>
              <%= link_to edit_booking_path(@booking.id), class: "btn orange-button" do %> <span class="large-icon"><i class="glyphicon glyphicon-edit"></i></span>
              <% end %>
            </div>
            <% end %>

          </div>
          <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane arrival"></i>
            </div>
          </div>
          <div class="col-sm-5">
            <div  class="top-down-pad">  ARRIVAL </div>
            <div><%= @booking.flight.arrival.name %> </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <div class="flight-time">
      <div class="top-down-pad">  TAKE OFF </div>
        <div><%= @booking.flight.departure_date %></div>
        <div><%= @booking.flight.departure_time %></div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="flight-time">
      <div class="top-down-pad">  REF: <%= @booking.ref %> </div>
        <div>COST: &#x20A6;<%= @booking.cost %></div>
        <div>SEATS: <%= @booking.seats %></div>
      </div>
    </div>
  </div>

</div>

app/views/partials/_userbookings.html.erb
  <div class="flights">
    <% unless flash['success'].blank?  %>
  <div class="alert alert-success success-booking" role="alert">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    <span class="sr-only">Success:</span>
    <%= flash['success'] %>
  </div>
  <% end %>
      <h3>PAST BOOKINGS</h3>
      <% @bookings.each do |booking| %>

      <div class="flight-pad">
    </div>
    <div class="row flight-list">
      <div class="col-sm-2">
      <div class="flight-airline">
      <span><%= booking.flight.airline %></span>
      </div>
      </div>
      <div class="col-sm-6">
        <div class="flight-detail">
          <div class="row">
            <div class="col-sm-1">
            <div class="top-down-pad">
            <i class="fa fa-plane"></i>
            </div>
            </div>
            <div class="col-sm-5">
              <div class="top-down-pad">  DEPARTURE </div>
              <div><%= booking.flight.departure.name %></div>
              <% if available?(booking.flight.departure_date) %>
              <div class="top-down-pad">
                <%= link_to booking_path(booking.id), class: "btn orange-button trash", method: :delete do %> <i class="glyphicon glyphicon-trash"></i>
                <% end %>
                <%= link_to edit_booking_path(booking.id), class: "btn orange-button edit" do %><i class="glyphicon glyphicon-edit"></i></span>
                <% end %>
              </div>
              <% end %>
            </div>
            <div class="col-sm-1">
              <div class="top-down-pad">
              <i class="fa fa-plane arrival"></i>
              </div>
            </div>
            <div class="col-sm-5">
              <div  class="top-down-pad">  ARRIVAL </div>
              <div><%= booking.flight.arrival.name %> </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="flight-time">
        <div class="top-down-pad">  TAKE OFF </div>
          <div><%= booking.flight.departure_date %></div>
          <div><%= booking.flight.departure_time %></div>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="flight-time">
        <div class="top-down-pad">  REF: <%= booking.ref %> </div>
          <div>COST: &#x20A6;<%= booking.cost %></div>
          <div>SEATS: <%= booking.seats %></div>
        </div>
      </div>
    </div>
    <% end %>

  </div>